"""
Contains configurations which will get executed
"""

SIMPLE_PROCESSING_TYPE = False
COMPLEX_PROCESSING_TYPE = False
VECTORIZE_DATA_SIMPLE = False
VECTORIZE_DATA_COMPLEX = True
MAX_SEQUENCE_LENGTH = 100
MAX_VOCAB_SIZE = 20000
EMBEDDING_DIM = 100
VALIDATION_SPLIT = 0.2
BATCH_SIZE = 128
EPOCHS = 10
GLOVE_PATH = "/Users/praveenkumar/Own_works/resources/nlp/glove"
