"""
Contains configurations which will get executed
"""

RAW_DATA_INGEST = False
SIMPLE_PROCESSING_TYPE = False
COMPLEX_PROCESSING_TYPE = False
VECTORIZE_DATA_SIMPLE = False
VECTORIZE_DATA_COMPLEX = False
SIMPLE_DATA_CLASSIFICATION = False
COMPLEX_DATA_CLASSIFICATION = True
MAX_SEQUENCE_LENGTH = 100
MAX_VOCAB_SIZE = 20000
EMBEDDING_DIM = 100
VALIDATION_SPLIT = 0.2
BATCH_SIZE = 64
EPOCHS = 200
EARLY_STOP_PATIENCE = 10
LOSS = "binary_crossentropy"
METRICS = "accuracy"
MODEL_NAME = "Model_"
MODEL_SAVE_FORMAT = ".h5"
GLOVE_PATH = "/Users/praveenkumar/Own_works/resources/nlp/glove"
CLASSES = ["threat"]
